apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-2ojy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-2ojy
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-2ojy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-2ojy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-2ojy
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qjkl-tenant/rhtap-demo-app/hacbs-test-project-2ojy@sha256:dab677651ce3b6cf4aa1abf4d7e7df8c3ceb3078eeb155583fbd8c926abeb74f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
