apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-2ojy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qjkl-tenant/rhtap-demo-app/hacbs-test-project-2ojy@sha256:dab677651ce3b6cf4aa1abf4d7e7df8c3ceb3078eeb155583fbd8c926abeb74f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
